#!/usr/bin/python3
# vim:se tw=0 sts=4 ts=4 et ai:
"""
Console script of imediff within package for testing.  Use as:

 $ python3 test_imediff.py ...

"""
import sys
sys.path.insert(0, '..')
import imediff

imediff.main()
