'\" t
.\"     Title: imediff2
.\"    Author: Jarno Elonen
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2006-03-10
.\"    Manual: imediff2 User Manual
.\"    Source: imediff2
.\"  Language: English
.\"
.TH "IMEDIFF2" "1" "2006\-03\-10" "imediff2" "imediff2 User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
imediff2 \- An interactive fullscreen 2\-way merge tool
.SH "SYNOPSIS"
.HP \w'\fBimediff2\fR\ 'u
\fBimediff2\fR [\fB\-m\fR] [\fB\-u\fR] [\fB\-a\fR] [\fB\-b\fR] [\fB\-c\fR] [\fB\-N\ \fR\fB\fInew\-file\fR\fR] [\fB\-o\ \fR\fB\fIoutputfile\fR\fR] {\fIfile1\fR} {\fIfile2\fR}
.SH "DESCRIPTION"
.PP
Merge two (slightly different) files interactively with a user friendly fullscreen interface in text mode\&.
.PP
Imediff2
shows the differences of given two files (in color if the terminal supports them), lets you scroll the file and toggle changes between old and new version one by one\&. If the \*(Aqunresolved\*(Aq mode is enabled, you can optionally save both versions\&.
.PP
Additionally, if the
\fI$EDITOR\fR
environment variable is set or if
\fB/usr/bin/editor\fR
exists and is executable, you can also launch an external editor and manually edit the half\-merged file before saving it, perhaps to resolve the \*(Aqunresolved\*(Aq parts\&.
.PP
Empty lines are shown in reverse colors so you see that you can select them\&. If a line is missing completely from one file,
imediff2
displays it as a reversed \*(Aq?\*(Aq\&. While it seems to take one line in the editing phase, it is naturally not saved into the output file\&.
.PP
To see a list of keyboard commands, hit
h
or
?
in the editor\&.
.PP
The program exits with status 0 if the changes were saved, 1 if the merging was aborted and 2 if the parameters were invalid\&.
.SH "OPTIONS"
.PP
\fB\-o \fR\fB\fIoutputfile\fR\fR, \fB\-\-output=\fR\fB\fIoutputfile\fR\fR
.RS 4
Write output to given file\&. If missing, changes will not be saved\&.
.RE
.PP
\fB\-N\fR, \fB\-\-new\-file\fR
.RS 4
Treat absent files as empty\&.
.RE
.PP
\fB\-m\fR, \fB\-\-mono\fR
.RS 4
Force monochrome display\&.
.RE
.PP
\fB\-u\fR, \fB\-\-unresolved\fR
.RS 4
Enable \*(Aqunresolved\*(Aq mode (see above)\&.
.RE
.PP
\fB\-a\fR
.RS 4
Start with version A (={\fIfile1\fR}) (default)\&.
.RE
.PP
\fB\-b\fR
.RS 4
Start with version B (={\fIfile1\fR})\&.
.RE
.PP
\fB\-c\fR
.RS 4
Start with unresolved changes (implies \-u)\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show summary of options and exit\&.
.RE
.PP
\fB\-V\fR, \fB\-\-version\fR
.RS 4
Show version and exit\&.
.RE
.SH "KEYBOARD COMMANDS"
.PP
The following keyboard commands are available in the editor\&.
.PP
h, ?
.RS 4
Show commands\&.
.RE
.PP
up, down, left, right
.RS 4
Move in document\&.
.RE
.PP
page up, page down
.RS 4
Move a screenfull\&.
.RE
.PP
enter
.RS 4
Toggle selected change\&.
.RE
.PP
n, tab, space
.RS 4
Jump to next change\&.
.RE
.PP
p
.RS 4
Jump to previous change\&.
.RE
.PP
a
.RS 4
Set current chunk to version A\&.
.RE
.PP
b
.RS 4
Set current chunk to version B\&.
.RE
.PP
u
.RS 4
Set current chunk to unresolved\&.
.RE
.PP
shift+a
.RS 4
Set all changes to version A\&.
.RE
.PP
shift+b
.RS 4
Set all changes to version B\&.
.RE
.PP
shift+u
.RS 4
Set all changes to unresolved\&.
.RE
.PP
e
.RS 4
Launch external editor\&.
.RE
.PP
r
.RS 4
Discard editor\-made changes\&. (Available only after
e\&.)
.RE
.PP
x, s
.RS 4
Save and exit\&.
.RE
.PP
q, ctrl+c
.RS 4
Exit without saving\&.
.RE
.PP
home, end
.RS 4
Jump to start or end\&.
.RE
.SH "FILE"
.PP
The key choices of the above keyboard commands can be configured in ~/\&.imediff2 which is created at the first execution of this command\&. The left side is the keys described in this manpage\&. The right side is your configuration choices\&. The current settings can be confirmed by the \*(Aqh\*(Aq key dialog\&.
.SH "SEE ALSO"
.PP
sdiff (1), diff (1), merge (1), diff3 (1)\&.
.SH "COPYRIGHT"
.PP
This manual page as well as the program itself was written by
Jarno Elonen
(<elonen@iki\&.fi>)\&. Unlike the program itself, which is licensed under the GNU General Public License (GPL) version 2 (or any later version, at your option), this document has been placed into the Public Domain\&.
.SH "AUTHOR"
.PP
\fBJarno Elonen\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2003-2006 elonen
.br
