#!/bin/sh -e
# Test code for programs installed to the system-wide
# Used by autopkgtest
#
# (This is not for python venv)
#
# check syntax of code browser start script
echo "Simple check of diff23lib library"
unset PYTHONPATH
python3 test/test_unittest_all.py -v 2>&1

echo "Copy imediff to here to avoid contaminating system "
cp /usr/bin/imediff ./
unset PYTHONPATH
echo "Syntax check of installed imediff"
python3 -m py_compile ./imediff
rm -f ./imediff
rm -rf ./__pycache__

echo "Syntax check of installed git-ime"
sh -n /usr/bin/git-ime

echo "Simple invocation check of imediff"
/usr/bin/imediff -h >/dev/null

echo "Simple invocation check of git-ime"
/usr/bin/git-ime -h >/dev/null
echo "============================================================"
echo
echo "Test results: OK"
echo
