'\" t
.\"     Title: git-ime
.\"    Author: Osamu Aoki
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2018-10-17
.\"    Manual: git-ime User Manual
.\"    Source: git-ime
.\"  Language: English
.\"
.TH "GIT\-IME" "1" "2018\-10\-17" "git-ime" "git-ime User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-ime \- An interactive git commit selection tool
.SH "SYNOPSIS"
.HP \w'\fBgit\-ime\fR\ 'u
\fBgit\-ime\fR {\fIfile\fR}
.SH "DESCRIPTION"
.PP
This is a simple shell wrapper script on
\fBimediff\fR
to make it work well with
\fBgit\fR
command\&.
.PP
If any local uncommitted change is found on
\fIfile\fR,
\fBimediff\fR
is executed with HEAD and local version of
\fIfile\fR\&. With
\fBimediff\fR, you can select a set of changes to the
\fIfile\fR
and to commit it to the git repository as a meaningful chunk\&. This script repeats this process until all changes are committed\&.
.PP
If no local uncommitted change is found on
\fIfile\fR,
\fBimediff\fR
is executed with HEAD^ and HEAD version of
\fIfile\fR\&. With
\fBimediff\fR, you can select a set of changes to the
\fIfile\fR
and to commit it to the git repository as a meaningful chunk\&. This script repeats this process until all changes are committed\&.
.PP
This
\fBgit\-ime\fR
is also useful during interactive execution of
\fBgit rebase \-i \fR\fB\fItreeish\fR\fR\&.
.PP
Please note this
\fBgit\-ime\fR
creates or overwrites
\fIfile\fR\&.tmp_a and
\fIfile\fR\&.tmp_b files\&. So they should not exist before execution of this command\&.
.SH "SEE ALSO"
.PP
imediff (1), git(1), and git\-rebase(1)\&.
.SH "COPYRIGHT"
.PP
This manual page as well as the program itself was written by
Osamu Aoki
(<osamu@debian\&.org>)\&. This document has been placed into the Public Domain\&.
.SH "AUTHOR"
.PP
\fBOsamu Aoki\fR
.RS 4
Original author of this script\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2018 osamu <osamu@debian\&.org>
.br
