#!/bin/sh -e

if [ "$1" = "configure" ]; then

  update-alternatives --install /usr/bin/merge2 merge2 /usr/bin/imediff2 70 \
    --slave /usr/share/man/man1/merge2.1.gz merge2.1.gz /usr/share/man/man1/imediff2.1.gz

fi

#DEBHELPER#
